# Generated by Django 5.2.3 on 2025-12-05 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
        ('ventas', '0004_venta_email_enviado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CobroCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_cobrado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Cobrado')),
                ('fecha_cobro', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque')], default='efectivo', max_length=20, verbose_name='Método de Pago')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros_realizados', to='ventas.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Cobro a Cliente',
                'verbose_name_plural': 'Cobros a Clientes',
                'ordering': ['-fecha_cobro'],
            },
        ),
    ]
