# Generated by Django 5.2.3 on 2025-12-05 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_cobrocliente'),
        ('inventario', '0011_compra_metodo_pago'),
        ('ventas', '0004_venta_email_enviado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagocompra',
            name='compra',
        ),
        migrations.CreateModel(
            name='CuentaPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total')),
                ('monto_cobrado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Cobrado')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Pendiente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pago Parcial'), ('PAGADA', 'Pagada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_por_cobrar', to='ventas.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Cuenta por Cobrar',
                'verbose_name_plural': 'Cuentas por Cobrar',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='AmortizacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField(verbose_name='Número de Cuota')),
                ('monto_cobrado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Cobrado')),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Anterior')),
                ('saldo_nuevo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Nuevo')),
                ('fecha_cobro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cobro')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque')], default='efectivo', max_length=20, verbose_name='Método de Pago')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referencia (Comprobante)')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortizaciones_cliente', to='finanzas.cuentaporcobrar', verbose_name='Cuenta por Cobrar')),
            ],
            options={
                'verbose_name': 'Amortización a Cliente',
                'verbose_name_plural': 'Amortizaciones a Clientes',
                'ordering': ['numero_cuota'],
                'unique_together': {('cuenta', 'numero_cuota')},
            },
        ),
        migrations.CreateModel(
            name='CuentaPorPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Pagado')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Pendiente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pago Parcial'), ('PAGADA', 'Pagada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('compra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_por_pagar', to='inventario.compra', verbose_name='Factura de Compra')),
            ],
            options={
                'verbose_name': 'Cuenta por Pagar',
                'verbose_name_plural': 'Cuentas por Pagar',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='AmortizacionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField(verbose_name='Número de Cuota')),
                ('monto_abonado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Abonado')),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Anterior')),
                ('saldo_nuevo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Nuevo')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque')], default='efectivo', max_length=20, verbose_name='Método de Pago')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referencia (Comprobante)')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortizaciones_proveedor', to='finanzas.cuentaporpagar', verbose_name='Cuenta por Pagar')),
            ],
            options={
                'verbose_name': 'Amortización a Proveedor',
                'verbose_name_plural': 'Amortizaciones a Proveedores',
                'ordering': ['numero_cuota'],
                'unique_together': {('cuenta', 'numero_cuota')},
            },
        ),
        migrations.DeleteModel(
            name='CobroCliente',
        ),
        migrations.DeleteModel(
            name='PagoCompra',
        ),
    ]
