# Generated by Django 5.2.3 on 2025-12-06 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_cliente_credito_activo_cliente_dias_plazo_and_more'),
        ('finanzas', '0003_remove_pagocompra_compra_cuentaporcobrar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_solicitado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Solicitado')),
                ('plazo_dias', models.IntegerField(default=30, verbose_name='Plazo (días)')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo o Descripción')),
                ('productos_detalle', models.TextField(blank=True, verbose_name='Productos a Financiar')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Respuesta')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado Por')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_credito', to='cliente.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Solicitud de Crédito',
                'verbose_name_plural': 'Solicitudes de Crédito',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
