# Generated by Django 5.2.6 on 2026-01-02 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_solicitudcredito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_cobrar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_pagar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_credito', to=settings.AUTH_USER_MODEL),
        ),
    ]
