# Generated by Django 6.0 on 2026-01-04 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_cuentaporcobrar_owner_cuentaporpagar_owner_and_more'),
        ('ventas', '0006_venta_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='venta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_por_cobrar', to='ventas.venta', verbose_name='Venta'),
        ),
    ]
