# Generated by Django 6.0 on 2026-01-04 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_cliente_user'),
        ('finanzas', '0006_alter_cuentaporcobrar_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_cobrar', to='cliente.cliente', verbose_name='Cliente'),
        ),
    ]
