from django import template

register = template.Library()

# Diccionario de traducciones de permisos
TRADUCCIONES_PERMISOS = {
    'Can add log entry': 'Puede agregar entrada de registro',
    'Can change log entry': 'Puede cambiar entrada de registro',
    'Can delete log entry': 'Puede eliminar entrada de registro',
    'Can view log entry': 'Puede ver entrada de registro',
    'Can add permission': 'Puede agregar permiso',
    'Can change permission': 'Puede cambiar permiso',
    'Can delete permission': 'Puede eliminar permiso',
    'Can view permission': 'Puede ver permiso',
    'Can add group': 'Puede agregar grupo',
    'Can change group': 'Puede cambiar grupo',
    'Can delete group': 'Puede eliminar grupo',
    'Can view group': 'Puede ver grupo',
    'Can add user': 'Puede agregar usuario',
    'Can change user': 'Puede cambiar usuario',
    'Can delete user': 'Puede eliminar usuario',
    'Can view user': 'Puede ver usuario',
    'Can add content type': 'Puede agregar tipo de contenido',
    'Can change content type': 'Puede cambiar tipo de contenido',
    'Can delete content type': 'Puede eliminar tipo de contenido',
    'Can view content type': 'Puede ver tipo de contenido',
    'Can add session': 'Puede agregar sesión',
    'Can change session': 'Puede cambiar sesión',
    'Can delete session': 'Puede eliminar sesión',
    'Can view session': 'Puede ver sesión',
    'Can add categoria': 'Puede agregar categoría',
    'Can change categoria': 'Puede cambiar categoría',
    'Can delete categoria': 'Puede eliminar categoría',
    'Can view categoria': 'Puede ver categoría',
    'Can add producto': 'Puede agregar producto',
    'Can change producto': 'Puede cambiar producto',
    'Can delete producto': 'Puede eliminar producto',
    'Can view producto': 'Puede ver producto',
    'Can add proveedor': 'Puede agregar proveedor',
    'Can change proveedor': 'Puede cambiar proveedor',
    'Can delete proveedor': 'Puede eliminar proveedor',
    'Can view proveedor': 'Puede ver proveedor',
    'Can add compra': 'Puede agregar compra',
    'Can change compra': 'Puede cambiar compra',
    'Can delete compra': 'Puede eliminar compra',
    'Can view compra': 'Puede ver compra',
    'Can add detalle compra': 'Puede agregar detalle de compra',
    'Can change detalle compra': 'Puede cambiar detalle de compra',
    'Can delete detalle compra': 'Puede eliminar detalle de compra',
    'Can view detalle compra': 'Puede ver detalle de compra',
    'Can add venta': 'Puede agregar venta',
    'Can change venta': 'Puede cambiar venta',
    'Can delete venta': 'Puede eliminar venta',
    'Can view venta': 'Puede ver venta',
    'Can add detalle venta': 'Puede agregar detalle de venta',
    'Can change detalle venta': 'Puede cambiar detalle de venta',
    'Can delete detalle venta': 'Puede eliminar detalle de venta',
    'Can view detalle venta': 'Puede ver detalle de venta',
    'Can add caja': 'Puede agregar caja',
    'Can change caja': 'Puede cambiar caja',
    'Can delete caja': 'Puede eliminar caja',
    'Can view caja': 'Puede ver caja',
    'Can add cliente': 'Puede agregar cliente',
    'Can change cliente': 'Puede cambiar cliente',
    'Can delete cliente': 'Puede eliminar cliente',
    'Can view cliente': 'Puede ver cliente',
    'Can add gasto': 'Puede agregar gasto',
    'Can change gasto': 'Puede cambiar gasto',
    'Can delete gasto': 'Puede eliminar gasto',
    'Can view gasto': 'Puede ver gasto',
    'Can add cuenta por cobrar': 'Puede agregar cuenta por cobrar',
    'Can change cuenta por cobrar': 'Puede cambiar cuenta por cobrar',
    'Can delete cuenta por cobrar': 'Puede eliminar cuenta por cobrar',
    'Can view cuenta por cobrar': 'Puede ver cuenta por cobrar',
    'Can add cuenta por pagar': 'Puede agregar cuenta por pagar',
    'Can change cuenta por pagar': 'Puede cambiar cuenta por pagar',
    'Can delete cuenta por pagar': 'Puede eliminar cuenta por pagar',
    'Can view cuenta por pagar': 'Puede ver cuenta por pagar',
    'Can add configuracion empresa': 'Puede agregar configuración de empresa',
    'Can change configuracion empresa': 'Puede cambiar configuración de empresa',
    'Can delete configuracion empresa': 'Puede eliminar configuración de empresa',
    'Can view configuracion empresa': 'Puede ver configuración de empresa',
    'Can add perfil usuario': 'Puede agregar perfil de usuario',
    'Can change perfil usuario': 'Puede cambiar perfil de usuario',
    'Can delete perfil usuario': 'Puede eliminar perfil de usuario',
    'Can view perfil usuario': 'Puede ver perfil de usuario',
    'Can add registro acceso': 'Puede agregar registro de acceso',
    'Can change registro acceso': 'Puede cambiar registro de acceso',
    'Can delete registro acceso': 'Puede eliminar registro de acceso',
    'Can view registro acceso': 'Puede ver registro de acceso',
    'Can add estado caja': 'Puede agregar estado de caja',
    'Can change estado caja': 'Puede cambiar estado de caja',
    'Can delete estado caja': 'Puede eliminar estado de caja',
    'Can view estado caja': 'Puede ver estado de caja',
}

@register.filter
def traducir_permiso(texto_permiso):
    """Traduce el texto de un permiso al español."""
    return TRADUCCIONES_PERMISOS.get(texto_permiso, texto_permiso)
