# Generated by Django 5.2.6 on 2025-09-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
