# Generated by Django 5.2.6 on 2025-09-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_producto_id_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='id_proveedor',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
