# Generated by Django 5.2.6 on 2025-11-16 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_producto_categoria_alter_producto_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Apertura')),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Inicial')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('monto_cierre_esperado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto de Cierre Esperado')),
                ('monto_cierre_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Real Contado al Cierre')),
                ('diferencia', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Diferencia (Sobrante/Faltante)')),
                ('abierta', models.BooleanField(default=True, verbose_name='Caja Abierta')),
                ('usuario_apertura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caja_aperturas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['-fecha_apertura'],
            },
        ),
    ]
