# Generated by Django 5.2.6 on 2025-11-16 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_caja'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Caja',
        ),
    ]
