# Generated by Django 5.2.6 on 2025-11-28 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_delete_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='requiere_caducidad',
            field=models.BooleanField(default=False, help_text='Indica si los productos en esta categoría requieren una fecha de caducidad.', verbose_name='Requiere Fecha de Caducidad'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_caducidad',
            field=models.DateField(blank=True, help_text='Fecha de caducidad del producto, si aplica.', null=True, verbose_name='Fecha de Caducidad'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventario.categoria'),
        ),
    ]
