# Generated by Django 5.2.3 on 2025-12-05 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_remove_producto_precio_producto_precio_costo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPagoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('CHEQUE', 'Cheque'), ('CREDITO', 'Crédito / A Plazo'), ('TARJETA', 'Tarjeta de Crédito/Débito (Empresa)'), ('OTRO', 'Otro')], max_length=50, unique=True, verbose_name='Método de Pago')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Método de Pago de Compra',
                'verbose_name_plural': 'Métodos de Pago de Compras',
            },
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='estado',
            field=models.CharField(choices=[], default='PENDIENTE', max_length=10),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='metodo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.metodopagocompra', verbose_name='Método de Pago'),
        ),
    ]
