# Generated by Django 5.2.6 on 2025-12-05 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_metodopagocompra_detallecompra_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompra',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='metodo_pago',
        ),
    ]
