# Generated by Django 5.2.6 on 2025-12-05 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_remove_detallecompra_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='metodo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.metodopagocompra', verbose_name='Método de Pago'),
        ),
    ]
