# Generated by Django 5.2.3 on 2025-12-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_compra_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha_pago_proveedor',
            field=models.DateField(blank=True, help_text='Fecha en que se debe pagar al proveedor (si es a crédito)', null=True, verbose_name='Fecha de Pago a Proveedor'),
        ),
    ]
