# Generated by Django 5.2.3 on 2025-12-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_compra_fecha_pago_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('DESCONTINUADO', 'Descontinuado')], default='ACTIVO', max_length=20, verbose_name='Estado del Producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tarifa_iva',
            field=models.CharField(choices=[(0, '0%'), (5, '5%'), (15, '15%'), ('NO_OBJETO', 'NO OBJETO IMPUESTO'), ('EXENTO', 'EXENTO IVA')], default=15, max_length=20, verbose_name='Tarifa IVA'),
        ),
    ]
