# Generated by Django 5.2.3 on 2025-12-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_producto_estado_producto_tarifa_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha_recibida',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se recibió la compra', null=True, verbose_name='Fecha de Recepción'),
        ),
    ]
