# Generated by Django 5.2.6 on 2025-12-13 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_alter_compra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='metodo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.metodopagocompra', verbose_name='Método de Pago'),
        ),
    ]
