# Generated by Django 5.2.6 on 2025-12-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_detallecompra_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='stock_actualizado',
            field=models.BooleanField(default=False, help_text='Indica si el stock del producto ya fue actualizado cuando la compra pasó a RECIBIDA', verbose_name='Stock Actualizado'),
        ),
    ]
