# Generated by Django 5.2.6 on 2025-12-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_detallecompra_stock_actualizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tarifa_iva',
            field=models.CharField(choices=[('0', '0%'), ('5', '5%'), ('15', '15%'), ('NO_OBJETO', 'NO OBJETO IMPUESTO'), ('EXENTO', 'EXENTO IVA')], default='15', max_length=20, verbose_name='Tarifa IVA'),
        ),
    ]
