# Generated by Django 5.2.6 on 2025-10-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('possitema', '0002_venta_antendido_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Control de Permiso POS', max_length=100)),
            ],
            options={
                'verbose_name': 'Permiso de Acceso',
                'verbose_name_plural': 'Permisos de Acceso',
                'permissions': [('can_view_dashboard_admin', 'Puede ver el Dashboard Administrativo completo (Reportes Críticos)'), ('can_view_lista_ventas', 'Puede ver el historial y listado de todas las ventas'), ('can_access_inventario', 'Puede acceder al módulo de inventario'), ('can_access_pos', 'Puede acceder al módulo de Punto de Venta (POS)')],
                'managed': False,
            },
        ),
    ]
