# Generated by Django 5.2.3 on 2025-11-26 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('possitema', '0004_caja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='antendido_por',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.AlterModelOptions(
            name='controlacceso',
            options={'managed': False, 'permissions': [('can_view_dashboard_admin', 'Puede ver el panel de administración'), ('can_view_lista_ventas', 'Puede ver la lista de ventas'), ('can_access_inventario', 'Puede acceder al inventario'), ('can_access_pos', 'Puede acceder al punto de venta')], 'verbose_name': 'Permiso de Acceso', 'verbose_name_plural': 'Permisos de Acceso'},
        ),
        migrations.DeleteModel(
            name='Caja',
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
