# Generated by Django 5.2.6 on 2025-12-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('possitema', '0005_remove_detalleventa_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('ruc', models.CharField(max_length=20, unique=True, verbose_name='RUC/NIT')),
                ('telefono_celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Celular')),
                ('telefono_convencional', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Convencional')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=12.0, max_digits=5, verbose_name='IVA (%)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/', verbose_name='Logo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuración de Empresa',
            },
        ),
    ]
