# Generated by Django 5.2.3 on 2025-12-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('possitema', '0006_configuracionempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='gmail_app_password',
            field=models.CharField(blank=True, help_text='Contraseña de 16 caracteres generada en tu cuenta de Google', max_length=100, null=True, verbose_name='Contraseña de Aplicación Gmail'),
        ),
    ]
