# Generated by Django 5.2.6 on 2026-01-17 02:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('possitema', '0008_configuracionempresa_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Bronce', 'Bronce'), ('Plata', 'Plata'), ('Oro', 'Oro')], max_length=20, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duracion_dias', models.PositiveIntegerField(default=30)),
                ('limite_usuarios', models.PositiveIntegerField(blank=True, help_text='Número máximo de usuarios permitidos', null=True)),
                ('limite_productos', models.PositiveIntegerField(blank=True, help_text='Número máximo de productos permitidos', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('esta_activa', models.BooleanField(default=True)),
                ('plan_actual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='possitema.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
