# Generated by Django 5.2.6 on 2026-01-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('possitema', '0010_registropago'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropago',
            name='numero_comprobante',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de comprobante'),
        ),
    ]
