# Generated by Django 5.2.6 on 2026-01-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('possitema', '0011_registropago_numero_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropago',
            name='comprobante_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Referencia bancaria'),
        ),
    ]
