# Generated by Django 5.2.6 on 2026-02-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('possitema', '0013_webhooklog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebhookLog',
        ),
        migrations.DeleteModel(
            name='ControlAcceso',
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='clave_firma_electronica',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Clave de Firma Electrónica'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='codigo_establecimiento_emisor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código del Establecimiento Emisor'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='codigo_punto_emision',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código del Punto de Emisión'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='contribuyente_especial',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Contribuyente Especial (Número de Resolución)'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='direccion_establecimiento_emisor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección del Establecimiento Emisor'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='direccion_establecimiento_matriz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección del Establecimiento Matriz'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Comercial'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='obligado_contabilidad',
            field=models.BooleanField(default=False, verbose_name='Obligado a Llevar Contabilidad'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='password_servidor_correo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Password del Servidor de Correo'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='puerto_servidor_correo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Puerto del Servidor de Correo'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='servidor_correo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Servidor de Correo'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='tipo_ambiente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de Ambiente'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='tipo_emision',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de Emisión'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='username_servidor_correo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Username del Servidor de Correo'),
        ),
    ]
