# Generated by Django 5.2.6 on 2026-02-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('possitema', '0014_delete_webhooklog_delete_controlacceso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionempresa',
            name='clave_firma_electronica',
            field=models.FileField(blank=True, null=True, upload_to='firmas_electronicas/', verbose_name='Firma electrónica (Archivo P12/PFX)'),
        ),
    ]
