# Generated by Django 5.2.6 on 2026-02-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('possitema', '0015_alter_configuracionempresa_clave_firma_electronica'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='password_p12_cifrado',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Contraseña P12 (Cifrada)'),
        ),
    ]
