# Generated by Django 5.2.6 on 2026-02-23 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('possitema', '0017_alter_configuracionempresa_password_p12_cifrado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespaldoDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(blank=True, max_length=200, verbose_name='Archivo')),
                ('tipo', models.CharField(choices=[('bd', 'Base de Datos'), ('media', 'Archivos Media'), ('completo', 'Completo (BD + Media)')], default='completo', max_length=20, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido'), ('en_proceso', 'En proceso')], default='en_proceso', max_length=20, verbose_name='Estado')),
                ('tamaño_mb', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tamaño (MB)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Respaldo',
                'verbose_name_plural': 'Respaldos de Base de Datos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
