# Generated by Django 5.2.6 on 2026-02-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('possitema', '0018_respaldodb'),
    ]

    operations = [
        migrations.AddField(
            model_name='respaldodb',
            name='checksum',
            field=models.CharField(blank=True, help_text='Hash SHA256 para verificación de integridad', max_length=64, verbose_name='Checksum SHA256'),
        ),
        migrations.AddField(
            model_name='respaldodb',
            name='ruta_archivo',
            field=models.CharField(blank=True, help_text='Ruta completa al archivo de respaldo', max_length=500, verbose_name='Ruta del archivo'),
        ),
    ]
