# Generated by Django 5.2.6 on 2026-02-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('possitema', '0019_add_checksum_ruta_to_respaldodb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRespaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.CharField(choices=[('desactivado', '❌ Desactivado'), ('cada_12h', '⏱ Cada 12 horas'), ('diario', '📅 Diario'), ('semanal', '📆 Semanal'), ('mensual', '🗓 Mensual')], default='desactivado', max_length=20, verbose_name='Frecuencia de respaldo')),
                ('hora', models.PositiveIntegerField(default=20, help_text='Hora del día (0-23) en que se ejecutará el respaldo. Ej: 20 = 8:00 PM', verbose_name='Hora del respaldo')),
                ('minuto', models.PositiveIntegerField(default=0, help_text='Minuto (0-59). Ej: 30 = a la media hora', verbose_name='Minuto')),
                ('dia_semana', models.PositiveIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], default=0, help_text='Solo aplica si la frecuencia es Semanal', verbose_name='Día de la semana (para semanal)')),
                ('dia_mes', models.PositiveIntegerField(default=1, help_text='Solo aplica si la frecuencia es Mensual (1-28)', verbose_name='Día del mes (para mensual)')),
                ('tipo_respaldo', models.CharField(choices=[('completo', 'Completo (BD + Media)'), ('bd', 'Solo Base de Datos')], default='completo', max_length=20, verbose_name='Tipo de respaldo')),
                ('ultimo_respaldo', models.DateTimeField(blank=True, null=True, verbose_name='Último respaldo automático')),
                ('respaldos_exitosos', models.PositiveIntegerField(default=0, verbose_name='Respaldos exitosos')),
                ('respaldos_fallidos', models.PositiveIntegerField(default=0, verbose_name='Respaldos fallidos')),
                ('activo', models.BooleanField(default=False, verbose_name='Programación activa')),
            ],
            options={
                'verbose_name': 'Configuración de Respaldo Automático',
                'verbose_name_plural': 'Configuración de Respaldo Automático',
            },
        ),
    ]
