# Generated by Django 5.2.6 on 2026-02-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('possitema', '0020_add_configuracion_respaldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='gmail_password_cifrado',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Gmail Password Cifrado'),
        ),
        migrations.AlterField(
            model_name='configuracionempresa',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='IVA (%)'),
        ),
    ]
