# Generated by Django 5.2.6 on 2026-02-25 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('possitema', '0021_configuracionempresa_gmail_password_cifrado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropago',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='possitema.plan'),
        ),
    ]
