# Generated by Django 5.2.6 on 2026-02-25 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('possitema', '0022_alter_registropago_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registropago',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='suscripcion',
            name='plan_actual',
        ),
        migrations.RemoveField(
            model_name='registropago',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='suscripcion',
            name='user',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='RegistroPago',
        ),
        migrations.DeleteModel(
            name='Suscripcion',
        ),
    ]
