# Generated by Django 5.2.3 on 2025-11-26 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('inventario', '0006_delete_caja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Control de Permiso POS', max_length=100)),
            ],
            options={
                'verbose_name': 'Permiso de Acceso',
                'verbose_name_plural': 'Permisos de Acceso',
                'permissions': [('can_view_dashboard_admin', 'Puede ver el Dashboard Administrativo completo (Reportes Críticos)'), ('can_view_lista_ventas', 'Puede ver el historial y listado de todas las ventas'), ('can_access_inventario', 'Puede acceder al módulo de inventario'), ('can_access_pos', 'Puede acceder al módulo de Punto de Venta (POS)')],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Apertura')),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Inicial')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('monto_cierre_esperado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto de Cierre Esperado')),
                ('monto_cierre_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Real Contado al Cierre')),
                ('diferencia', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Diferencia (Sobrante/Faltante)')),
                ('abierta', models.BooleanField(default=True, verbose_name='Caja Abierta')),
                ('usuario_apertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caja_aperturas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('antendido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Atendido por')),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_realizadas', to='ventas.caja')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle_venta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
    ]
