# Generated by Django 5.2.6 on 2025-11-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='costo_al_vender',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo unitario registrado'),
        ),
    ]
