# Generated by Django 5.2.3 on 2025-11-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_detalleventa_costo_al_vender'),
    ]

    operations = [
        # Comentado: RemoveField causa problema con foreign key en MySQL
        # migrations.RemoveField(
        #     model_name='caja',
        #     name='id',
        # ),
        # migrations.AddField(
        #     model_name='caja',
        #     name='id_caja',
        #     field=models.AutoField(primary_key=True, serialize=False),
        # ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('mixto', 'Mixto')], default='efectivo', max_length=20, verbose_name='Método de Pago'),
        ),
    ]
