# Generated by Django 5.2.3 on 2025-12-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_remove_caja_id_caja_id_caja_venta_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='email_enviado',
            field=models.BooleanField(default=False, verbose_name='Email Enviado'),
        ),
    ]
