# Generated by Django 5.2.3 on 2025-12-05 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_venta_email_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='es_credito',
            field=models.BooleanField(default=False, verbose_name='¿Es a Crédito?'),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado_credito',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pago Parcial'), ('PAGADA', 'Pagada')], default='PENDIENTE', max_length=20, verbose_name='Estado del Crédito'),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto a Crédito'),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Pagado'),
        ),
        migrations.AddField(
            model_name='venta',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas de Venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('credito', 'Crédito'), ('mixto', 'Mixto')], default='efectivo', max_length=20, verbose_name='Método de Pago Principal'),
        ),
        migrations.CreateModel(
            name='MetodoPagoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('credito', 'Crédito')], max_length=20, verbose_name='Método de Pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referencia (Nro. Tarjeta, Cheque, etc)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago_usados', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Método de Pago de Venta',
                'verbose_name_plural': 'Métodos de Pago de Venta',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
