# Generated by Django 5.2.6 on 2026-02-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_venta_anulado_por_venta_estado_venta_fecha_anulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='subido_sri_manual',
            field=models.BooleanField(default=False, verbose_name='Subido manualmente al SRI'),
        ),
    ]
