# Generated by Django 5.2.3 on 2025-12-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_direccion_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ruc_cedula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='RUC/Cédula'),
        ),
    ]
