# Generated by Django 5.2.3 on 2025-12-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cliente_ruc_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='credito_activo',
            field=models.BooleanField(default=False, verbose_name='¿Tiene Crédito?'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dias_plazo',
            field=models.IntegerField(default=30, verbose_name='Días de Plazo para Pago'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Límite de Crédito'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='saldo_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo de Crédito Disponible'),
        ),
    ]
