# Generated by Django 5.2.3 on 2025-12-06 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_estadocaja_registroasistencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroAsistencia',
        ),
    ]
