# Generated by Django 5.2.3 on 2025-12-08 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_delete_registroasistencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('LOGIN', 'Entrada'), ('LOGOUT', 'Salida')], max_length=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('duracion_sesion', models.DurationField(blank=True, help_text='Duración de la sesión en minutos', null=True)),
                ('ip_address', models.CharField(blank=True, help_text='IP del cliente', max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Información del navegador/cliente', null=True)),
                ('notas', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_acceso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['user', '-fecha_hora'], name='usuarios_re_user_id_eee1d8_idx'), models.Index(fields=['tipo_evento', '-fecha_hora'], name='usuarios_re_tipo_ev_fff35b_idx')],
            },
        ),
    ]
