# Generated by Django 5.2.6 on 2026-03-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RespaldoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20)),
                ('tamano', models.FloatField()),
                ('checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('creado_por', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Respaldo de Base de Datos',
                'verbose_name_plural': 'Respaldos de Base de Datos',
            },
        ),
    ]
