"""
Django settings for possitema project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys

try:
    import google.generativeai as genai
except ImportError:
    genai = None



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# Intentar cargar variables de entorno desde .env (opcional)
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    # Si dotenv no está instalado, continuar sin él (usa SQLite por defecto)
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-key-cambiar-en-produccion'
    else:
        raise RuntimeError('SECRET_KEY no configurada. Define la variable de entorno SECRET_KEY.')

ALLOWED_HOSTS = ['respectful-comfort-production-34a4.up.railway.app', '.up.railway.app', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'inventario',
    'cliente',
    'possitema',
    'usuarios',
    'control',
    'reportes',
    'ventas',
    'finanzas',
    'gasto',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'possitema.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'possitema.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# 
# PostgreSQL - Compatible con Railway y desarrollo local

import dj_database_url

# Si Railway provee DATABASE_URL, usarla automáticamente
DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    # Railway / Producción → usa la URL que Railway provee
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            ssl_require=True  # Obligatorio para herramientas externas como pg_dump en Railway
        )
    }
else:
    # Desarrollo local → PostgreSQL local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'sistemados_db'),
            'USER': os.getenv('DB_USER', 'sistema_user'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'sistema123'),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': int(os.getenv('DB_PORT', '5433')),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de Email
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.tu-servidor.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'usuario@dominio.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'tu_password')
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@dominio.com')

# Optimización de archivos estáticos (Compresión y caché)
STORAGES = {
    # Esta es la parte que te falta y causa el KeyError: 'default'
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    # Esta es la que ya tenías para los estilos CSS/JS
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

LOGOUT_REDIRECT_URL = '/usuarios/login/'
APPEND_SLASH = True

CSRF_TRUSTED_ORIGINS = [
    'https://respectful-comfort-production-34a4.up.railway.app',
    'https://*.up.railway.app',
    'http://localhost',
    'http://127.0.0.1',
]

# Redirección correcta para login_required
LOGIN_URL = '/usuarios/login/'
# Configuración de Gemini AI
import logging
logger = logging.getLogger(__name__)

GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')
GEMINI_MODEL = None

if GEMINI_API_KEY and genai:
    try:
        genai.configure(api_key=GEMINI_API_KEY)
        GEMINI_MODEL = genai.GenerativeModel('gemini-1.5-flash')
        logger.info("Gemini AI configurado exitosamente con el modelo 1.5-flash.")
    except Exception as e:
        logger.warning(f"Error al configurar Gemini: {e}")
elif not genai:
    logger.info("google-generativeai no instalado. La IA de ventas estará desactivada.")
else:
    logger.info("GEMINI_API_KEY no encontrada. La IA de ventas estará desactivada.")


# Ruta absoluta para los respaldos dentro del contenedor de Railway
BACKUP_ROOT = os.path.join(BASE_DIR, 'backup', 'respaldos')

# Crear la carpeta automáticamente si no existe al iniciar la app
if not os.path.exists(BACKUP_ROOT):
    os.makedirs(BACKUP_ROOT, exist_ok=True)
