# Generated by Django 5.2.3 on 2025-12-06 03:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id_gasto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción del Gasto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('fecha_gasto', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Gasto')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=20)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='gastos/', verbose_name='Comprobante')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha_gasto'],
            },
        ),
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('ADMINISTRACION', 'Gastos de Administración'), ('VENTA', 'Gastos de Venta'), ('OTRO', 'Otros Gastos')], max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Gasto',
                'verbose_name_plural': 'Tipos de Gasto',
            },
        ),
        migrations.CreateModel(
            name='DetalleGastoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('SALARIO_VENDEDOR', 'Salarios de Vendedores'), ('COMISION', 'Comisiones'), ('PUBLICIDAD', 'Publicidad y Marketing'), ('EMPAQUE', 'Material de Empaque'), ('TRANSPORTE', 'Transporte y Distribución'), ('PROMOCION', 'Promociones y Descuentos'), ('OTROS', 'Otros')], max_length=50)),
                ('beneficiario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Beneficiario')),
                ('canal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Canal (Redes Sociales, TV, Radio, etc.)')),
                ('gasto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_venta', to='gasto.gasto')),
            ],
            options={
                'verbose_name': 'Detalle Gasto Venta',
                'verbose_name_plural': 'Detalles Gastos Venta',
            },
        ),
        migrations.CreateModel(
            name='DetalleGastoAdministracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('SALARIO', 'Salarios del Personal'), ('ALQUILER', 'Alquiler de Oficina'), ('SERVICIOS', 'Servicios Básicos (Luz, Agua, Internet)'), ('SEGUROS', 'Seguros'), ('IMPUESTOS', 'Impuestos y Licencias'), ('MANTENIMIENTO', 'Mantenimiento de Equipos'), ('CAPACITACION', 'Capacitación del Personal'), ('OTROS', 'Otros')], max_length=50)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsable')),
                ('gasto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_admin', to='gasto.gasto')),
            ],
            options={
                'verbose_name': 'Detalle Gasto Administración',
                'verbose_name_plural': 'Detalles Gastos Administración',
            },
        ),
        migrations.AddField(
            model_name='gasto',
            name='tipo_gasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gasto.tipogasto', verbose_name='Tipo de Gasto'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['tipo_gasto', 'fecha_gasto'], name='gasto_gasto_tipo_ga_f46de4_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['estado', 'fecha_gasto'], name='gasto_gasto_estado_b4c053_idx'),
        ),
    ]
