# Generated by Django 5.2.6 on 2026-01-02 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gasto', '0003_remove_gasto_user_detallegastoadministracion_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipogasto',
            old_name='user',
            new_name='owner',
        ),
    ]
