# Generated by Django 5.2.3 on 2025-12-06 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('hora_entrada', models.TimeField(blank=True, null=True, verbose_name='Hora Entrada')),
                ('timestamp_entrada', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp Entrada')),
                ('ip_entrada', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP Entrada')),
                ('hora_salida', models.TimeField(blank=True, null=True, verbose_name='Hora Salida')),
                ('timestamp_salida', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp Salida')),
                ('ip_salida', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP Salida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_asistencia', to=settings.AUTH_USER_MODEL, verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'ordering': ['-fecha', '-timestamp_entrada'],
                'unique_together': {('usuario', 'fecha')},
            },
        ),
    ]
